const CONFIG = {
  OMDB_API_KEY: process.env.REACT_APP_OMDB_API_KEY,
  TMDB_API_KEY: process.env.REACT_APP_TMDB_API_KEY,
  TMDB_BEARER_TOKEN: process.env.REACT_APP_TMDB_BEARER_TOKEN,
};

export { CONFIG };